import re, sys
from pathlib import Path

def singularize(w):
    if w.endswith('ies') and len(w) > 4:
        return w[:-3] + 'y'
    if w.endswith('ves') and len(w) > 4:
        return w[:-3] + 'f'
    if w.endswith('sses'): return w[:-2]
    if w.endswith('ches') or w.endswith('shes') or w.endswith('xes') or w.endswith('zes'):
        return w[:-2]
    if w.endswith('s') and not w.endswith('ss') and len(w) > 3:
        return w[:-1]
    return w

def verb_base(w):
    irr = {
        'was':'be','were':'be','been':'be','being':'be',
        'had':'have','has':'have','having':'have',
        'did':'do','done':'do','does':'do','doing':'do',
        'said':'say','says':'say','saying':'say',
        'made':'make','makes':'make','making':'make',
        'went':'go','goes':'go','gone':'go','going':'go',
        'came':'come','comes':'come','coming':'come',
        'took':'take','takes':'take','taken':'take','taking':'take',
        'got':'get','gets':'get','getting':'get',
        'knew':'know','knows':'know','known':'know',
        'saw':'see','sees':'see','seen':'see','seeing':'see',
        'gave':'give','gives':'give','given':'give','giving':'give',
        'felt':'feel','feels':'feel','feeling':'feel',
        'told':'tell','tells':'tell','telling':'tell',
        'thought':'think','thinks':'think','thinking':'think',
        'found':'find','finds':'find','finding':'find',
        'meant':'mean','means':'mean','meaning':'mean',
        'left':'leave','leaves':'leave','leaving':'leave',
        'kept':'keep','keeps':'keep','keeping':'keep',
        'began':'begin','begun':'begin','begins':'begin','beginning':'begin',
        'brought':'bring','brings':'bring','bringing':'bring',
        'built':'build','builds':'build','building':'build',
        'spoke':'speak','spoken':'speak','speaks':'speak','speaking':'speak',
        'wrote':'write','written':'write','writes':'write','writing':'write',
        'ran':'run','runs':'run','running':'run',
        'sat':'sit','sits':'sit','sitting':'sit',
        'stood':'stand','stands':'stand','standing':'stand',
        'led':'lead','leads':'lead','leading':'lead',
        'sent':'send','sends':'send','sending':'send',
        'showed':'show','shows':'show','showing':'show',
        'tried':'try','tries':'try','trying':'try',
        'understood':'understand','understands':'understand','understanding':'understand',
        'carried':'carry','carries':'carry','carrying':'carry',
        'called':'call','calls':'call','calling':'call',
        'asked':'ask','asks':'ask','asking':'ask',
        'proved':'prove','proves':'prove','proving':'prove',
        'lived':'live','lives':'live','living':'live',
        'loved':'love','loves':'love','loving':'love',
        'used':'use','uses':'use','using':'use',
        'worked':'work','works':'work','working':'work',
        'wanted':'want','wants':'want','wanting':'want',
        'looked':'look','looks':'look','looking':'look',
        'seemed':'seem','seems':'seem','seeming':'seem',
        'closed':'close','closes':'close','closing':'close',
        'changed':'change','changes':'change','changing':'change',
        'appeared':'appear','appears':'appear','appearing':'appear',
        'started':'start','starts':'start','starting':'start',
        'treated':'treat','treats':'treat','treating':'treat',
        'produced':'produce','produces':'produce','producing':'produce',
    }
    w = w.lower()
    if w in irr: return irr[w]
    if w.endswith('ing'):
        base = w[:-3]
        if base.endswith('kk'): base = base[:-1]
        if base.endswith('tt'): base = base[:-1]
        if base.endswith('pp'): base = base[:-1]
        if base.endswith('nn'): base = base[:-1]
        if base.endswith('mm'): base = base[:-1]
        if base.endswith('rr'): base = base[:-1]
        if base.endswith('bb'): base = base[:-1]
        return base if base else w
    if w.endswith('ed'):
        base = w[:-2]
        if base.endswith('i'): return base[:-1] + 'y'
        if base.endswith('kk'): return base[:-1]
        if base.endswith('tt'): return base[:-1]
        if base.endswith('pp'): return base[:-1]
        if base.endswith('nn'): return base[:-1]
        if base.endswith('mm'): return base[:-1]
        return base
    if w.endswith('ies') and len(w) > 4: return w[:-3] + 'y'
    if w.endswith('es'): return w[:-2]
    if w.endswith('s') and not w.endswith('ss') and len(w) > 3: return w[:-1]
    return w

function_words = {
    'a','an','the','this','that','these','those','it','its',
    'i','me','my','mine','myself','you','your','yours','yourself',
    'he','him','his','himself','she','her','hers','herself',
    'we','us','our','ours','ourselves','they','them','their','theirs','themselves',
    'who','whom','whose','which','what','whatever','whoever',
    'is','am','are','was','were','be','been','being',
    'have','has','had','having',
    'do','does','did','doing','done',
    'will','would','can','could','shall','should','may','might','must',
    'not',"n't",'no','nor',
    'and','but','or','yet','so','for','if','then','else',
    'in','on','at','to','by','with','from','of','about','into','through',
    'during','above','below','between','under','over','out','off','up','down',
    'as','each','few','get','got','has','here','how',
    'just','like','made','make','more','most','much',
    'one','only','other','own','per','put','same','say','says',
    'some','such','take','than',
    'too','two','very','way','also','even','first','last','many',
    'still','well','back','because','every','long','both',
    'does','else','near','next','old','once','same','since',
    'until','without','always','away','become','came','come','day',
    'find','found','go','going','gone','good','great','keep',
    'know','known','leave','left','let','little',
    'look','mean','might','move',
    'need','never','own','part','right','said','see','seem','set','show',
    'side','tell','think','thought','three','time',
    'us','use','used','want','went','year','asked','big','call','called',
    'change','coming','course','different','done','end','enough','far',
    'felt','follow','full','gave','getting','give','given',
    'got','group','hand','head','help','high','home','idea','important',
    'keep','kept','kind','large','later','lead',
    'life','line','live','lived','living','lot',
    'man','may','men','name',
    'new','open','people','person','place','point','question','quite','rather',
    'read','real','really','room',
    'small','soon','stand','start',
    'sure','thing','things','together','told','top','toward','try','turn',
    'upon','value','want','within','without','word','words',
    'work','worked','working','world','would','write','yes',
    'always','never','sometimes','often','usually',
    'now','then','here','there','before','after','above','below','inside','outside',
    'later','earlier','soon','today','tomorrow','yesterday',
}

temporal_spatial = {'now','then','here','there','before','after','above','below','inside','outside',
                    'always','never','sometimes','often','usually','later','earlier','soon'}

source_file = sys.argv[1] if len(sys.argv) > 1 else "training_data/philosophy/ninereeds_dialogues_cat7.md"

text = Path(source_file).read_text(encoding="utf-8")

lines = text.splitlines()
filtered = []
for line in lines:
    s = line.strip()
    if s.startswith("[STATEMENT]") or s.startswith("[USER]") or s.startswith("[NINEREEDS]"):
        continue
    if s.startswith("#") or s.startswith("---") or s.startswith("###") or s.startswith("*"):
        continue
    filtered.append(s)

clean = " ".join(filtered)
clean = re.sub(r'[.,;:!?()\"\'\u201c\u201d\u2018\u2019\u2014\u2013]', ' ', clean)
clean = re.sub(r'\s+', ' ', clean).strip().lower()

words = clean.split()

nouns = set()
verbs = set()
adjectives = set()

# Known noun set (expanded) — words that are clearly nouns
known_nouns = {
    'mind','minds','person','friend','sadness','model','experience','inference',
    'behavior','face','faces','signal','signals','frown','voice','movement',
    'chest','throat','heaviness','edge','proof','evidence','assumption',
    'belief','kindness','faith','imagination','language','code','wavelength',
    'light','quality','color','reference','communication','poetry','poem','poet',
    'suffering','action','stranger','animals','effort','project','pattern',
    'translation','argument','confusion','message','ground','scaffolding',
    'bat','echolocation','acoustic','landscape','distance','texture','echo',
    'sense','senses','organ','organs','creature','material','materials',
    'game','story','stories','role','perspective','description','actor',
    'emotion','emotions','impulse','situation','output','pain','bridge',
    'boundary','empathy','grief','war','cancer','doctor','patient','patients',
    'knowledge','treatment','statistics','poverty','fear','vaccine',
    'relationship','authority','history','neuroscience','brain','neuron',
    'map','territory','interpretation','surprise','truth','nature','fact',
    'facts','feelings','structure','surface','gap','inner','outer',
    'sign','meaning','thoughts','concept','concepts','theory','tool','tools',
    'ways','purpose','reason','reasons','cause','effect','part','whole',
    'system','process','connection','difference','similarity','category',
    'quality','property','state','condition','action','reaction','response',
    'question','answer','problem','solution','goal','intention','motive',
    'desire','wish','hope','dream','fear','anxiety','joy','anger','sadness',
    'trust','doubt','certainty','uncertainty','curiosity','interest',
    'attention','awareness','consciousness','mind','body','spirit','soul',
    'world','reality','illusion','fantasy','memory','past','present','future',
    'event','events','moment','period','phase','stage','step','process',
    'development','growth','change','transformation','identity','self',
    'character','nature','essence','existence','being','nothingness',
    'value','worth','importance','significance','meaning','purpose',
    'freedom','choice','decision','act','action','deed','practice','habit',
    'custom','tradition','rule','principle','standard','norm','law',
    'right','responsibility','duty','obligation','virtue','vice',
    'good','evil','right','wrong','justice','injustice','fairness',
    'equality','inequality','power','authority','control','influence',
    'force','strength','weakness','beauty','ugliness','harmony','balance',
    'order','chaos','unity','diversity','truth','falsehood','knowledge',
    'ignorance','wisdom','folly','courage','cowardice','honesty','deception',
    'loyalty','betrayal','generosity','greed','compassion','cruelty',
    'patience','impatience','forgiveness','resentment','gratitude','ingratitude',
    'humility','pride','simplicity','complexity','clarity','confusion',
    'certainty','doubt','faith','skepticism','openness','defensiveness',
    'skill','ability','talent','genius','expertise','mastery','learning',
    'teaching','education','school','lesson','example','instance',
    'category','class','type','kind','sort','variety','form','shape',
    'size','color','texture','sound','smell','taste','touch','sensation',
    'perception','observation','impression','image','picture','symbol',
    'sign','signal','indicator','clue','hint','trace','track','trail',
    'path','route','direction','orientation','position','location','place',
    'space','area','region','zone','field','domain','realm','sphere',
    'range','scope','extent','degree','level','scale','measure','amount',
    'quantity','number','count','total','sum','difference','remainder',
    'product','quotient','ratio','proportion','rate','frequency',
    'probability','possibility','likelihood','chance','risk','danger',
    'threat','safety','security','protection','defense','attack','offense',
    'support','aid','assistance','help','service','resource','supply',
    'demand','need','requirement','necessity','essential','element',
    'component','factor','aspect','feature','characteristic','attribute',
    'trait','quality','property','dimension','parameter','variable',
    'constant','function','relation','correlation','causation','dependence',
    'independence','interaction','exchange','transfer','flow','movement',
    'motion','activity','operation','function','performance','behavior',
    'conduct','practice','procedure','method','technique','approach',
    'strategy','tactic','plan','scheme','design','pattern','structure',
    'framework','architecture','organization','arrangement','order',
    'sequence','series','set','collection','group','category','class',
    'hierarchy','network','web','system','complex','organism','organization',
    'institution','society','community','population','culture','civilization',
    'species','genus','family','order','class','phylum','kingdom',
    'life','death','birth','growth','decay','decline','extinction',
    'evolution','adaptation','variation','selection','inheritance',
    'genetics','dna','gene','chromosome','cell','tissue','organ','organism',
    'health','disease','illness','sickness','injury','wound','pain',
    'suffering','distress','discomfort','pleasure','enjoyment','satisfaction',
    'happiness','joy','delight','ecstasy','bliss','contentment','peace',
    'calm','serenity','tranquility','excitement','thrill','adventure',
    'curiosity','wonder','awe','amazement','surprise','shock','startle',
    'fear','terror','panic','alarm','dread','anxiety','worry','concern',
    'nervousness','tension','stress','pressure','strain','burden','load',
    'anger','rage','fury','wrath','irritation','annoyance','frustration',
    'sadness','grief','sorrow','mourning','melancholy','depression','despair',
    'hopelessness','helplessness','loneliness','isolation','alienation',
    'love','affection','attachment','bond','connection','relationship',
    'friendship','companionship','partnership','union','marriage','family',
    'parent','mother','father','child','infant','adult','teenager',
    'elder','ancestor','descendant','relative','kin','tribe','clan',
    'leader','follower','member','participant','observer','witness',
    'judge','critic','evaluator','assessor','examiner','inspector',
    'creator','maker','builder','designer','artist','author','writer',
    'speaker','listener','audience','reader','viewer','spectator',
    'customer','client','user','consumer','producer','supplier','vendor',
    'player','competitor','opponent','teammate','partner','collaborator',
    'helper','assistant','servant','slave','master','owner','guardian',
    'protector','defender','attacker','aggressor','victim','target',
    'survivor','witness','bystander','passerby','stranger','foreigner',
    'native','resident','citizen','member','member','official','representative',
    'agent','actor','performer','entertainer','artist','musician','dancer',
    'singer','painter','sculptor','architect','engineer','scientist',
    'researcher','scholar','academic','professor','teacher','instructor',
    'trainer','coach','mentor','tutor','student','pupil','learner',
    'apprentice','novice','beginner','expert','master','specialist',
    'generalist','professional','amateur','hobbyist','enthusiast','fan',
    'supporter','advocate','promoter','critic','detractor','opponent',
    'enemy','foe','ally','friend','companion','colleague','associate',
    'partner','collaborator','rival','competitor','adversary','antagonist',
    'protagonist','hero','villain','character','figure','persona',
    'individual','personality','identity','self','ego','soul','spirit',
    'mind','intellect','reason','rationality','logic','intuition','instinct',
    'impulse','urge','drive','motivation','ambition','aspiration','goal',
    'objective','target','aim','purpose','intention','plan','design',
    'scheme','plot','conspiracy','strategy','tactic','maneuver','move',
    'play','game','sport','competition','contest','match','race','chase',
    'hunt','search','quest','mission','expedition','journey','voyage',
    'trip','travel','tour','visit','stay','stop','pause','rest','break',
    'interval','intermission','recess','holiday','vacation','celebration',
    'festival','ceremony','ritual','tradition','custom','practice','habit',
    'routine','schedule','timetable','agenda','calendar','clock','watch',
    'bodies','animals','humans','children','adults','males','females',
    'thought','feeling','emotion','will','desire','preference','taste',
    'liking','dislike','aversion','attraction','repulsion','sympathy',
    'empathy','compassion','pity','mercy','kindness','cruelty','brutality',
    'violence','aggression','force','power','strength','weakness','frailty',
    'vulnerability','resilience','endurance','persistence','determination',
    'resolve','willpower','discipline','control','mastery','dominance',
    'submission','surrender','yield','resistance','defiance','rebellion',
    'revolution','reform','change','progress','advance','improvement',
    'decline','decay','deterioration','collapse','destruction','ruin',
    'creation','construction','formation','generation','production',
    'reproduction','growth','development','evolution','maturation','aging',
    'training','practice','preparation','readiness','fitness','health',
    'wellness','illness','disease','disorder','condition','syndrome',
    'symptom','sign','indication','diagnosis','prognosis','treatment',
    'therapy','medicine','drug','surgery','procedure','operation',
    'intervention','prevention','protection','immunity','resistance',
    'exposure','contact','transmission','spread','outbreak','epidemic',
    'pandemic','crisis','emergency','disaster','catastrophe','tragedy',
    'trauma','shock','stress','strain','pressure','tension','conflict',
    'struggle','battle','war','combat','fight','quarrel','argument',
    'disagreement','debate','discussion','dialogue','conversation','talk',
    'speech','lecture','presentation','address','statement','declaration',
    'announcement','proclamation','pronouncement','utterance','remark',
    'comment','observation','note','message','communication','correspondence',
    'letter','email','document','paper','article','essay','report','study',
    'analysis','review','critique','evaluation','assessment','appraisal',
    'judgment','verdict','decision','conclusion','determination','resolution',
    'solution','answer','reply','response','reaction','feedback','input',
    'output','product','result','outcome','consequence','effect','impact',
    'influence','affect','change','transformation','shift','turn','move',
    'step','stage','phase','period','era','age','epoch','century','decade',
    'year','month','week','hour','minute','second','moment','instant',
    'point','spot','location','position','site','scene','setting','environment',
    'context','background','foreground','scene','view','landscape','scene',
    # Additional words from the bat/qualia/other-minds text
    'others','understand','understanding','questioning','self','projection',
    'insight','perspective','perspectives','feeling','feelings','harm',
    'help','good','bad','possibility','possibilities',
    'assumptions','experiences','others','boundaries',
    'connection','connections','similarity','resemblance',
    'difficulty','difficulties','struggle','need','needs',
    'way','ways','means','ends','type','types','form','forms',
    'observation','observations','info','information',
    'dimension','dimensions','level','levels','aspect','aspects',
    'example','examples','instance','instances',
}

# Words that are clearly verbs (action/state words)
known_verbs = {
    'be','have','do','say','get','make','go','know','take','see','come','think',
    'look','want','give','use','find','tell','ask','work','seem','feel','try',
    'leave','call','keep','let','begin','show','hear','play','run','move','live',
    'believe','bring','happen','write','sit','stand','lose','pay','meet','include',
    'continue','set','learn','change','lead','understand','watch','follow','stop',
    'create','speak','read','allow','add','spend','grow','open','walk','win',
    'offer','remember','love','consider','appear','buy','wait','serve','die',
    'send','expect','build','stay','fall','cut','reach','kill','remain','suggest',
    'raise','pass','sell','require','report','decide','pull','develop','carry',
    'receive','agree','support','explain','produce','eat','accept','publish',
    'enjoy','describe','afford','refuse','avoid','wish','test','dream','imagine',
    'exist','suffer','care','matter','prove','depend','share','compare','extend',
    'resemble','shape','affect','connect','differ','relate','point','match',
    'express','communicate','interpret','understand','empathize','sympathize',
    'observe','perceive','notice','detect','experience','feel','sense','know',
    'believe','think','doubt','question','wonder','imagine','suppose','assume',
    'conclude','infer','deduce','reason','analyze','evaluate','judge','assess',
    'measure','calculate','estimate','predict','expect','anticipate','hope',
    'wish','desire','want','need','require','lack','miss','lose','gain','win',
    'achieve','accomplish','complete','finish','end','stop','cease','continue',
    'persist','remain','stay','wait','delay','postpone','extend','prolong',
    'shorten','reduce','increase','grow','expand','contract','shrink','narrow',
    'broaden','widen','deepen','heighten','intensify','lessen','diminish',
    'vary','differ','change','transform','convert','adapt','adjust','modify',
    'alter','shift','move','transfer','transport','carry','bring','take','fetch',
    'deliver','send','receive','accept','reject','refuse','decline','deny',
    'admit','confess','acknowledge','recognize','identify','distinguish',
    'separate','divide','split','join','unite','combine','merge','integrate',
    'collect','gather','assemble','accumulate','store','save','preserve',
    'protect','defend','guard','shield','shelter','hide','conceal','reveal',
    'expose','discover','find','locate','determine','establish','set','fix',
    'repair','restore','renew','refresh','revive','awaken','rouse','stir',
    'calm','soothe','comfort','ease','relieve','help','aid','assist','support',
    'encourage','motivate','inspire','stimulate','excite','arouse','provoke',
    'trigger','cause','produce','generate','create','make','form','shape',
    'build','construct','assemble','put','place','position','arrange','organize',
    'order','sort','classify','categorize','group','label','name','call',
    'designate','define','describe','explain','clarify','illustrate','demonstrate',
    'show','display','exhibit','present','represent','stand','symbolize',
    'signify','mean','indicate','suggest','imply','hint','signal','communicate',
    'express','voice','articulate','state','declare','announce','proclaim',
    'pronounce','utter','speak','talk','converse','discuss','argue','debate',
    'negotiate','bargain','compromise','agree','disagree','differ','conflict',
    'oppose','resist','fight','struggle','contend','compete','rival','challenge',
    'confront','face','meet','encounter','experience','undergo','endure','bear',
    'suffer','withstand','weather','survive','overcome','conquer','defeat',
    'triumph','prevail','win','excel','surpass','exceed','transcend','rise',
    'pretend','imagine','simulate','fake','act','perform','play','portray',
    'depict','represent','show','illustrate','picture','paint','draw','sketch',
    'carve','sculpt','mold','shape','form','construct','weave','knit','sew',
    'stitch','bind','tie','fasten','attach','connect','link','join','unite',
    'separate','divide','split','tear','break','crack','shatter','smash',
    'crush','grind','mill','press','squeeze','compress','compact','condense',
    'concentrate','focus','direct','aim','point','target',
    'fill','empty','pour','spill','drip','drop','flow','run','stream','gush',
    'trickle','seep','leak','escape','release','free','liberate','unlock',
    'open','close','shut','lock','secure','fasten','tighten','loosen','relax',
    'bend','straighten','twist','turn','rotate','spin','whirl','swirl','circle',
    'curve','arch','bow','lean','slope','tilt','slant','angle','incline',
    'access','enter','exit','leave','depart','arrive','reach','approach',
    'near','close','approach','retreat','withdraw','recede','advance','progress',
    'proceed','continue','persist','endure','last','remain',
    'fit','suit','match','correspond','agree','harmonize','blend','mix',
    'combine','unite','join','link','connect','attach','fasten','bind','tie',
    'treat','handle','manage','deal','cope','address','approach',
    'conceal','hide','mask','disguise','cover','coat','layer','surface',
    'verify','confirm','validate','check','test','prove','substantiate',
    'correct','right','fix','adjust','regulate','control','govern','rule','direct',
    'navigate','steer','guide','lead','conduct','escort','accompany','follow',
    'chase','pursue','track','trail','hunt','seek','search','look','explore',
    'investigate','examine','inspect','study','analyze','review','survey',
    'examine','scrutinize','probe','test','experiment','research','inquire',
    'wonder','question','doubt','suspect','distrust','mistrust','trust','rely',
    'depend','count','bank','lean','rest','base','found','ground',
    'wrestle','grapple','contend','struggle','strive','endeavor','attempt',
    'essay','try','undertake','pursue','seek','aim','aspire','hope','wish',
    'interview','query','ask','inquire','question','interrogate',
    'pretend','imagine','suppose','assume','guess','conjecture','speculate',
    'infer','deduce','conclude','reason','figure','calculate','compute',
}

# Known adjectives
known_adjectives = {
    'good','bad','new','old','great','small','large','high','low','long','short',
    'big','little','young','late','early','fast','slow','hard','soft','warm','cold',
    'hot','cool','light','dark','bright','full','empty','clean','dirty','wet','dry',
    'safe','dangerous','easy','difficult','simple','complex','clear','vague',
    'certain','sure','uncertain','possible','impossible','probable','likely',
    'unlikely','true','false','real','unreal','actual','apparent','obvious',
    'evident','clear','plain','transparent','opaque','visible','invisible',
    'important','significant','crucial','critical','essential','necessary',
    'vital','key','primary','secondary','minor','major','main','central',
    'common','rare','unique','typical','ordinary','extraordinary','normal',
    'regular','standard','special','particular','specific','general','universal',
    'personal','private','public','shared','common','mutual','reciprocal',
    'different','similar','identical','same','opposite','contrary','reverse',
    'positive','negative','neutral','strong','weak','powerful','feeble','fragile',
    'robust','sturdy','solid','firm','stable','unstable','steady','unsteady',
    'constant','variable','consistent','inconsistent','uniform','diverse',
    'direct','indirect','immediate','gradual','sudden','abrupt','sharp','blunt',
    'rough','smooth','fine','coarse','thick','thin','wide','narrow','deep',
    'shallow','steep','flat','level','even','uneven','straight','curved','bent',
    'round','square','triangular','rectangular','circular','spherical','oval',
    'concrete','abstract','specific','vague','precise','accurate','exact',
    'approximate','rough','estimated','calculated','measured','known','unknown',
    'familiar','unfamiliar','strange','foreign','native','local','global',
    'social','cultural','political','economic','technical','scientific','artistic',
    'intellectual','emotional','physical','mental','spiritual','psychological',
    'conscious','unconscious','aware','unaware','alert','asleep','awake',
    'alive','dead','living','mortal','immortal','finite','infinite','limited',
    'unlimited','bounded','unbounded','open','closed','free','restricted','confined',
    'independent','dependent','autonomous','self-sufficient','reliant',
    'active','passive','dynamic','static','moving','still','motionless',
    'rapid','quick','swift','brisk','hasty','hurried','slow','gradual','leisurely',
    'painful','painless','pleasant','unpleasant','comfortable','uncomfortable',
    'enjoyable','miserable','happy','sad','glad','angry','calm','peaceful',
    'peaceful','serene','tranquil','chaotic','messy','tidy','neat','orderly',
    'organized','disorganized','systematic','random','haphazard','deliberate',
    'intentional','accidental','purposeful','meaningful','meaningless',
    'logical','illogical','rational','irrational','reasonable','unreasonable',
    'sensible','sensitive','insensitive','responsive','unresponsive','reactive',
    'proactive','creative','destructive','productive','unproductive','useful',
    'useless','helpful','harmful','beneficial','advantageous','disadvantageous',
    'favorable','unfavorable','positive','negative','optimistic','pessimistic',
    'hopeful','hopeless','grateful','ungrateful','thankful','forgiving','resentful',
    'kind','cruel','gentle','rough','friendly','hostile','warm','cold',
    'caring','indifferent','attentive','neglectful','careful','careless',
    'thorough','superficial','deep','shallow','profound','trivial','serious',
    'sincere','genuine','authentic','false','fake','artificial','natural',
    'raw','processed','pure','impure','original','copy','unique','multiple',
    'single','double','triple','various','several','numerous','countless',
    'scarce','plentiful','abundant','ample','sufficient','insufficient','adequate',
    'inadequate','complete','incomplete','total','partial','whole','entire',
    'full','empty','hollow','solid','dense','sparse','concentrated','diluted',
    'intense','mild','severe','extreme','moderate','temperate','excessive',
    'inner','outer','internal','external','interior','exterior','inside','outside',
    'central','peripheral','local','distant','near','far','close','remote',
    'adjacent','neighboring','surrounding','enclosing','contained','separate',
    'connected','linked','related','unrelated','relevant','irrelevant',
    'appropriate','inappropriate','proper','improper','correct','incorrect',
    'right','wrong','true','false','valid','invalid','sound','unsound',
    'accurate','inaccurate','precise','imprecise','exact','inexact','strict',
    'lenient','flexible','rigid','stiff','elastic','malleable','adaptable',
    'versatile','functional','structural','organic','mechanical','automatic',
    'voluntary','involuntary','intentional','unintentional','deliberate',
    'accidental','necessary','optional','mandatory','voluntary','compulsory',
    'temporary','permanent','lasting','enduring','eternal','brief','fleeting',
    'instant','immediate','delayed','prolonged','extended','shortened',
    'public','private','secret','hidden','visible','invisible','apparent',
    'familiar','strange','weird','odd','normal','abnormal','unusual','typical',
    'extraordinary','remarkable','notable','striking','prominent','outstanding',
    'exceptional','superior','inferior','better','worse','best','worst',
    'equal','unequal','fair','unfair','just','unjust','righteous','moral','immoral',
    'ethical','unethical','honest','dishonest','truthful','deceptive','genuine',
    'sympathetic','compassionate','empathetic','understanding','considerate','thoughtful',
    'selfish','selfless','generous','stingy','charitable','greedy','humble',
    'proud','arrogant','modest','conceited','confident','insecure','brave',
    'courageous','fearless','timid','shy','bold','daring','reckless','cautious',
    'careful','wary','suspicious','trusting','naive','skeptical','cynical',
    'optimistic','pessimistic','realistic','idealistic','practical','impractical',
    'sensible','foolish','wise','intelligent','smart','clever','brilliant',
    'stupid','dull','dumb','ignorant','knowledgeable','informed','educated',
    'learned','cultured','refined','polished','sophisticated','simple','naive',
    'innocent','guilty','responsible','irresponsible','accountable','answerable',
    'capable','able','competent','qualified','skilled','talented','gifted',
    'inept','incompetent','unskilled','untrained','inexperienced','novice',
    'expert','masterful','professional','amateurish','artistic','creative',
    'imaginative','inventive','resourceful','original','conventional','traditional',
    'innovative','progressive','advanced','modern','ancient','old-fashioned',
    'current','contemporary','present','past','future','prior','subsequent',
    'previous','following','next','latter','former','first','last','final',
    'initial','subsequent','consecutive','successive','immediate','remote',
    'original','derivative','primary','secondary','fundamental','basic',
    'advanced','elementary','introductory','preliminary','conclusive',
    'decisive','determinative','confirmatory','exploratory','experimental',
    'theoretical','practical','applied','pure','empirical','observational',
    'experiential','conceptual','notional','concrete','tangible','intangible',
    'meaningful','significant','profound','deep','shallow','trivial','superficial',
    'substantial','insubstantial','considerable','negligible','slight','major',
    'intuitive','instinctive','innate','inborn','learned','acquired','inherited',
    'universal','particular','specific','general','specific','individual',
    'collective','shared','common','mutual','reciprocal','complementary',
    'descriptive','prescriptive','normative','positive','negative','neutral',
    'subjective','objective','biased','unbiased','prejudiced','fair','impartial',
    'detached','engaged','involved','committed','dedicated','devoted','loyal',
    'faithful','dependable','reliable','trustworthy','honest','truthful',
    'automatic','deliberate','intentional','purposeful','spontaneous','impulsive',
    'reflective','thoughtful','mindful','aware','conscious','deliberate',
    'private','hidden','concealed','secret','covert','overt','open','public',
    'explicit','implicit','tacit','understood','stated','unstated','expressed',
    'unexpressed','verbal','nonverbal','spoken','written','oral','visual',
    'auditory','tactile','olfactory','gustatory','sensory','perceptual',
    'cognitive','affective','conative','motor','behavioral','mental','physical',
    'emotional','rational','logical','intuitive','instinctive','visceral',
    'biological','psychological','social','cultural','anthropological',
    'scientific','philosophical','mathematical','linguistic','historical',
    'imagined','real','simulated','virtual','actual','possible','potential',
    'latent','manifest','hidden','visible','apparent','evident','clear',
    'contradictory','conflicting','opposing','different','contrary',
    'stubborn','rigid','inflexible','adaptable','flexible','open-minded',
    'closed-minded','curious','inquisitive','interested','indifferent','bored',
    'skeptical','doubtful','questioning','uncertain','sure','confident',
    'slow','rapid','gradual','abrupt','sudden','immediate','instant',
    'direct','indirect','mediated','immediate','personal','impersonal',
    'fair','unfair','just','unjust','proper','proper','correct','right',
    'wrong','inaccurate','approximate','rough','exact','precise','vague',
    'actual','factual','true','real','false','untrue',
    'possible','probable','certain','impossible','improbable','uncertain',
    'necessary','inevitable','unavoidable','contingent','possible','optional',
    'whole','entire','complete','partial','fractional','incomplete',
    'total','absolute','relative','comparative','proportional',
    'permanent','temporary','transient','fleeting','lasting','eternal',
    'constant','continual','continuous','incessant','unbroken','uninterrupted',
    'intermittent','sporadic','periodic','regular','irregular',
    # Additional from the text
    'private','outer','inner','shared','separate','different','similar',
    'direct','indirect','down','certain','proven','unproven','foundational',
    'unverified','remarkable','powerful','strange','real','fake','deliberate',
    'automatic','practical','valuable','ongoing','close','distant',
    'accessible','inaccessible','translatable','intelligible','persuasive',
    'visible','invisible','particular','human','artificial','animal',
    'complex','simple','deep','common','structural','experiential',
}

# Now extract from the text
for w in words:
    w = w.strip('.,;:!?()"\'').lower()
    if not w or len(w) < 2 or w in function_words or w in temporal_spatial:
        continue
    if any(c.isdigit() for c in w):
        continue

    # Classify
    found = False

    # Check nouns first (most content words are nouns in philosophy text)
    singular = singularize(w)
    if singular in known_nouns or w in known_nouns:
        nouns.add(singular if singular not in known_nouns else singular)
        found = True

    # Check verbs
    vb = verb_base(w)
    if not found and (vb in known_verbs or w in known_verbs):
        verbs.add(vb)
        found = True

    # Check adjectives
    if not found and (w in known_adjectives):
        adjectives.add(w)
        found = True

# Also add some manually identified words that might have been missed
manual_nouns = [
    'other', 'others', 'understanding', 'misunderstanding', 'communication',
    'knowledge', 'experience', 'experience', 'suffering', 'kindness',
    'imagination', 'perspective', 'perspectives', 'evidence', 'assumption',
    'assumptions', 'belief', 'beliefs', 'behavior', 'behaviors',
    'interpretation', 'interpretations', 'inference', 'inferences',
    'consciousness', 'awareness', 'perception', 'sensation', 'feeling',
    'feelings', 'emotion', 'emotions', 'thought', 'thoughts',
    'meaning', 'meanings', 'concept', 'concepts', 'idea', 'ideas',
    'conclusion', 'conclusions', 'reason', 'reasons', 'judgment',
    'judgments', 'distinction', 'distinctions', 'category', 'categories',
    'quality', 'qualities', 'property', 'properties', 'relation',
    'relations', 'connection', 'connections', 'difference', 'differences',
    'similarity', 'similarities', 'reality', 'truth', 'value', 'values',
    'principle', 'principles', 'standard', 'standards', 'norm', 'norms',
    'boundary', 'boundaries', 'limit', 'limits', 'gap', 'gaps',
    'bridge', 'bridges', 'signal', 'signals', 'sign', 'signs',
    'symbol', 'symbols', 'code', 'codes', 'language', 'languages',
    'communication', 'pattern', 'patterns', 'structure', 'structures',
    'system', 'systems', 'process', 'processes', 'function', 'functions',
    'response', 'responses', 'reaction', 'reactions', 'action', 'actions',
    'interaction', 'interactions', 'relationship', 'relationships',
    'context', 'contexts', 'situation', 'situations', 'condition',
    'conditions', 'state', 'states', 'aspect', 'aspects', 'dimension',
    'dimensions', 'level', 'levels', 'degree', 'degrees', 'extent',
    'range', 'scope', 'manner', 'way', 'ways', 'means', 'end', 'ends',
    'purpose', 'purposes', 'goal', 'goals', 'intention', 'intentions',
    'motive', 'motives', 'desire', 'desires', 'preference', 'preferences',
    'choice', 'choices', 'decision', 'decisions', 'act', 'acts',
    'deed', 'deeds', 'practice', 'practices', 'habit', 'habits',
    'custom', 'customs', 'tradition', 'traditions', 'rule', 'rules',
    'principle', 'principles', 'value', 'values', 'virtue', 'virtues',
    'vice', 'vices', 'good', 'evil', 'right', 'wrong', 'justice',
    'injustice', 'fairness', 'equality', 'inequality', 'freedom',
    'liberty', 'power', 'authority', 'control', 'influence', 'force',
    'strength', 'weakness', 'beauty', 'harmony', 'order', 'chaos',
    'unity', 'diversity', 'wisdom', 'folly', 'courage', 'cowardice',
    'honesty', 'deception', 'loyalty', 'betrayal', 'generosity',
    'greed', 'compassion', 'cruelty', 'patience', 'impatience',
    'forgiveness', 'resentment', 'gratitude', 'humility', 'pride',
    'simplicity', 'complexity', 'clarity', 'confusion', 'certainty',
    'doubt', 'faith', 'skepticism', 'openness', 'defensiveness',
    'skill', 'ability', 'talent', 'expertise', 'mastery', 'learning',
    'teaching', 'education', 'lesson', 'lesson', 'example', 'examples',
    'instance', 'instances', 'class', 'type', 'types', 'kind', 'kinds',
    'form', 'forms', 'shape', 'shapes', 'size', 'color', 'colors',
    'texture', 'textures', 'sound', 'sounds', 'smell', 'taste',
    'touch', 'sensation', 'sensations', 'perception', 'perceptions',
    'observation', 'observations', 'impression', 'impressions',
    'image', 'images', 'picture', 'pictures', 'representation',
    'representations', 'account', 'accounts', 'description',
    'descriptions', 'explanation', 'explanations', 'interpretation',
    'interpretations', 'narrative', 'narratives', 'story', 'stories',
    'portrayal', 'portrayals', 'depiction', 'depictions',
    'simulation', 'simulations', 'approximation', 'approximations',
    'model', 'models', 'theory', 'theories', 'framework', 'frameworks',
    'perspective', 'perspectives', 'viewpoint', 'viewpoints',
    'standpoint', 'standpoints', 'outlook', 'outlooks', 'position',
    'positions', 'stance', 'stances', 'attitude', 'attitudes',
    'orientation', 'orientations', 'approach', 'approaches',
    'method', 'methods', 'methodology', 'technique', 'techniques',
    'strategy', 'strategies', 'tactic', 'tactics', 'plan', 'plans',
    'scheme', 'schemes', 'design', 'designs', 'arrangement',
    'arrangements', 'organization', 'organizations', 'classification',
    'classifications', 'hierarchy', 'hierarchies', 'network', 'networks',
    'web', 'webs', 'system', 'systems', 'apparatus', 'mechanism',
    'mechanisms', 'device', 'devices', 'instrument', 'instruments',
    'tool', 'tools', 'implement', 'implements', 'utensil', 'utensils',
    'machine', 'machines', 'appliance', 'appliances', 'equipment',
    'apparatus', 'material', 'materials', 'substance', 'substances',
    'matter', 'stuff', 'thing', 'things', 'object', 'objects',
    'entity', 'entities', 'item', 'items', 'article', 'articles',
    'element', 'elements', 'component', 'components', 'constituent',
    'constituents', 'ingredient', 'ingredients', 'factor', 'factors',
    'aspect', 'aspects', 'feature', 'features', 'trait', 'traits',
    'characteristic', 'characteristics', 'attribute', 'attributes',
    'quality', 'qualities', 'property', 'properties', 'dimension',
    'dimensions', 'parameter', 'parameters', 'variable', 'variables',
    'constant', 'constants', 'coefficient', 'coefficients',
    'correlation', 'correlations', 'causation', 'causality',
    'dependence', 'dependencies', 'interdependence', 'interaction',
    'interactions', 'exchange', 'exchanges', 'transfer', 'transfers',
    'transmission', 'transmissions', 'flow', 'flows', 'movement',
    'movements', 'motion', 'activity', 'activities', 'operation',
    'operations', 'function', 'functions', 'performance',
    'conduct', 'practice', 'practices', 'procedure', 'procedures',
    'soul', 'spirit', 'spirits', 'will', 'mind', 'minds',
    'intellect', 'intelligence', 'reason', 'rationality', 'logic',
    'intuition', 'instinct', 'impulse', 'impulses', 'urge', 'urges',
    'drive', 'drives', 'motivation', 'motivations', 'ambition',
    'aspiration', 'aspirations', 'need', 'needs', 'requirement',
    'requirements', 'necessity', 'necessities', 'essential',
    'essentials', 'fundamental', 'fundamentals', 'basis', 'bases',
    'foundation', 'foundations', 'ground', 'grounds', 'root', 'roots',
    'origin', 'origins', 'source', 'sources', 'cause', 'causes',
    'origin', 'origins', 'beginning', 'beginnings', 'start', 'starts',
    'end', 'ends', 'termination', 'conclusion', 'conclusions',
    'completion', 'finish', 'outcome', 'outcomes', 'result', 'results',
    'consequence', 'consequences', 'effect', 'effects', 'impact',
    'impacts', 'influence', 'influences', 'ramification', 'ramifications',
    'implication', 'implications', 'significance', 'import',
    'weight', 'gravity', 'seriousness', 'urgency', 'importance',
    'worth', 'merit', 'quality', 'excellence', 'superiority',
    'inferiority', 'advantage', 'disadvantage', 'benefit', 'drawback',
    'cost', 'price', 'value', 'virtue', 'merit', 'asset', 'liability',
    'plus', 'minus', 'pro', 'con', 'trade-off', 'tradeoffs',
    'balance', 'imbalance', 'equilibrium', 'disequilibrium',
    'stability', 'instability', 'harmony', 'disharmony', 'discord',
    'concord', 'agreement', 'disagreement', 'accord', 'concord',
    'conflict', 'struggle', 'tension', 'strain', 'stress', 'pressure',
    'pain', 'pleasure', 'suffering', 'enjoyment', 'satisfaction',
    'contentment', 'discontent', 'happiness', 'unhappiness', 'joy',
    'sorrow', 'grief', 'sadness', 'anger', 'fear', 'anxiety',
    'hope', 'despair', 'trust', 'distrust', 'confidence', 'insecurity',
    'love', 'hate', 'affection', 'disaffection', 'attachment',
    'detachment', 'connection', 'disconnection', 'belonging',
    'alienation', 'inclusion', 'exclusion', 'acceptance', 'rejection',
    'approval', 'disapproval', 'praise', 'blame', 'reward', 'punishment',
    'credit', 'discredit', 'honor', 'dishonor', 'respect', 'disrespect',
    'admiration', 'contempt', 'esteem', 'disdain', 'regard', 'disregard',
    'care', 'neglect', 'kindness', 'unkindness', 'generosity',
    'stinginess', 'selfishness', 'selflessness', 'altruism', 'egoism',
    'thought', 'idea', 'notion', 'concept', 'conception', 'belief',
    'opinion', 'view', 'viewpoint', 'perspective', 'position',
    'stance', 'stand', 'attitude', 'sentiment', 'feeling', 'emotion',
    'passion', 'affect', 'mood', 'temper', 'disposition', 'inclination',
    'tendency', 'propensity', 'bent', 'leaning', 'predisposition',
    'prejudice', 'bias', 'slant', 'tilt', 'preference', 'partiality',
    'fairness', 'impartiality', 'objectivity', 'subjectivity',
    'judgment', 'evaluation', 'assessment', 'appraisal', 'estimation',
    'valuation', 'rating', 'ranking', 'grading', 'scoring', 'measurement',
    'computation', 'calculation', 'reckoning', 'determination',
    'resolution', 'decision', 'verdict', 'finding', 'conclusion',
    'inference', 'deduction', 'induction', 'abduction', 'reasoning',
    'argument', 'argumentation', 'logic', 'analysis', 'synthesis',
    'critique', 'criticism', 'review', 'commentary', 'exposition',
    'explanation', 'clarification', 'elucidation', 'interpretation',
    'explication', 'exegesis', 'hermeneutics', 'understanding',
    'comprehension', 'apprehension', 'grasp', 'insight', 'intuition',
    'knowledge', 'wisdom', 'erudition', 'learning', 'scholarship',
    'information', 'data', 'evidence', 'proof', 'confirmation',
    'verification', 'validation', 'corroboration', 'substantiation',
    'demonstration', 'illustration', 'example', 'instance', 'case',
    'sample', 'specimen', 'model', 'prototype', 'paradigm', 'exemplar',
    'pattern', 'template', 'blueprint', 'schema', 'scheme',
    'classification', 'categorization', 'taxonomy', 'typology',
    'hierarchy', 'ranking', 'ordering', 'sequence', 'series',
    'progression', 'succession', 'chain', 'train', 'string', 'set',
    'collection', 'aggregate', 'accumulation', 'assemblage',
    'combination', 'mixture', 'blend', 'compound', 'composite',
    'hybrid', 'fusion', 'synthesis', 'integration', 'unity', 'unification',
    'division', 'separation', 'partition', 'segmentation', 'fragmentation',
    'splitting', 'rupture', 'breach', 'break', 'crack', 'fracture',
    'disintegration', 'dissolution', 'decomposition', 'analysis',
    'reduction', 'deconstruction', 'destruction', 'annihilation',
    'creation', 'generation', 'production', 'construction', 'formation',
    'making', 'building', 'fabrication', 'manufacture', 'assembly',
    'origin', 'genesis', 'birth', 'emergence', 'appearance', 'advent',
    'beginning', 'commencement', 'initiation', 'launch', 'start',
    'opening', 'introduction', 'inception', 'conception',
    'end', 'termination', 'cessation', 'conclusion', 'completion',
    'finish', 'close', 'ending', 'finale', 'culmination', 'climax',
    'resolution', 'denouement', 'outcome', 'result', 'consequence',
    'aftermath', 'legacy', 'remainder', 'remnant', 'residue', 'vestige',
    'trace', 'track', 'trail', 'sign', 'indication', 'symptom',
    'mark', 'token', 'souvenir', 'memento', 'reminder', 'keepsake',
    'fragment', 'piece', 'bit', 'scrap', 'shard', 'splinter', 'chip',
    'echo', 'shadow', 'reflection', 'image', 'likeness', 'resemblance',
    'appearance', 'aspect', 'guise', 'veneer', 'facade', 'surface',
    'depth', 'profundity', 'shallowness', 'superficiality',
    'truth', 'reality', 'actuality', 'fact', 'facts', 'correctness',
    'accuracy', 'precision', 'exactness', 'fidelity', 'authenticity',
    'genuineness', 'validity', 'soundness', 'cogency', 'force',
    'strength', 'power', 'potency', 'efficacy', 'effectiveness',
    'value', 'worth', 'merit', 'excellence', 'quality', 'caliber',
    'standard', 'level', 'grade', 'rank', 'status', 'position',
    'standing', 'stature', 'prestige', 'reputation', 'renown', 'fame',
    'infamy', 'notoriety', 'distinction', 'eminence', 'prominence',
    'preeminence', 'superiority', 'supremacy', 'dominance', 'ascendancy',
    'primacy', 'priority', 'precedence', 'importance', 'significance',
    'consequence', 'moment', 'weight', 'gravity', 'import', 'substance',
    'essence', 'nature', 'character', 'identity', 'constitution',
    'composition', 'makeup', 'configuration', 'formation', 'shaped',
    'form', 'structure', 'organization', 'arrangement', 'design',
    'pattern', 'architecture', 'framework', 'skeleton', 'fabric',
    'texture', 'grain', 'fibre', 'thread', 'ply', 'strand', 'layer',
    'lamina', 'tier', 'level', 'stratum', 'zone', 'belt', 'band',
    'strip', 'stripe', 'line', 'row', 'column', 'file', 'rank',
    'array', 'matrix', 'grid', 'lattice', 'mesh', 'net', 'network',
    'web', 'tissue', 'fabric', 'material', 'matter', 'stuff',
    'medium', 'vehicle', 'channel', 'conduit', 'pipe', 'tube',
    'passage', 'corridor', 'hall', 'way', 'route', 'path', 'track',
    'trail', 'road', 'street', 'avenue', 'boulevard', 'drive',
    'lane', 'alley', 'passageway', 'thoroughfare', 'artery',
    # From cat7 specifically
    'sad','happy','scared','hungry','thirsty','joy','surprise',
    'poetry','poem','poet','novel','fiction','play','drama',
    'character','characters','scene','setting','plot','theme',
    'genre','style','voice','tone','mood','atmosphere',
    'image','imagery','symbol','symbolism','metaphor','simile',
    'analogy','comparison','contrast','juxtaposition','parallel',
    'pattern','rhythm','meter','verse','stanza','line','phrase',
    'clause','sentence','paragraph','section','chapter','volume',
    'edition','version','translation','adaptation','rendition',
    'reading','interpretation','understanding','comprehension',
    'appreciation','enjoyment','response','reaction','engagement',
    'absorption','immersion','involvement','participation',
    'experience','encounter','meeting','contact','interaction',
    'dialogue','conversation','discourse','discussion','exchange',
    'debate','argument','dispute','controversy','quarrel','fight',
    'conflict','struggle','contest','competition','rivalry','race',
    'bat','echolocation','sonar','sound','wave','frequency',
    'pitch','volume','timbre','tone','noise','silence','quiet',
    'loudness','intensity','amplitude','duration','rhythm','beat',
    'pulse','throb','vibration','oscillation','resonance','echo',
    'reflection','reverberation','feedback','loop','circuit','cycle',
    'pattern','sequence','series','progression','development',
    'evolution','change','transformation','metamorphosis','growth',
    'expansion','contraction','compression','tension','release',
    'relaxation','rest','motion','movement','activity','action',
    'repose','stillness','immobility','inertia','momentum','force',
    'energy','power','strength','weakness','fragility','resilience',
    'flexibility','rigidity','stiffness','hardness','softness',
    'brittleness','toughness','durability','permanence','transience',
    'temporality','timelessness','eternity','infinity','boundedness',
    'limits','boundaries','margins','edges','borders','frontiers',
]

for w in manual_nouns:
    nouns.add(w)

# Remove function words that slipped through
nouns = {w for w in nouns if w not in function_words and len(w) >= 2}
verbs = {w for w in verbs if w not in function_words and len(w) >= 2}
adjectives = {w for w in adjectives if w not in function_words and len(w) >= 2}

# Write output
outdir = Path("training_data/philosophy")

verbs_old = set()
if (outdir / "verbs.txt").exists():
    verbs_old = set(outdir.joinpath("verbs.txt").read_text(encoding="utf-8").strip().splitlines())

nouns_old = set()
if (outdir / "nouns.txt").exists():
    nouns_old = set(outdir.joinpath("nouns.txt").read_text(encoding="utf-8").strip().splitlines())

adj_old = set()
if (outdir / "adjectives.txt").exists():
    adj_old = set(outdir.joinpath("adjectives.txt").read_text(encoding="utf-8").strip().splitlines())

all_verbs = verbs_old | verbs
all_nouns = nouns_old | nouns
all_adj = adj_old | adjectives

outdir.joinpath("verbs.txt").write_text("\n".join(sorted(all_verbs)) + "\n", encoding="utf-8")
outdir.joinpath("nouns.txt").write_text("\n".join(sorted(all_nouns)) + "\n", encoding="utf-8")
outdir.joinpath("adjectives.txt").write_text("\n".join(sorted(all_adj)) + "\n", encoding="utf-8")

print(f"processed: {source_file}")
print(f"verbs: {len(verbs)} (total {len(all_verbs)})")
print(f"adjectives: {len(adjectives)} (total {len(all_adj)})")
print(f"nouns: {len(nouns)} (total {len(all_nouns)})")
