#!/usr/bin/env bash
set -euo pipefail

PYTHON="${PYTHON:-/home/aomukai/.unsloth/studio/unsloth_studio/bin/python}"

# Defaults
RESUME="core/wiki_level1_from_phase1plus3_150m_e3.pt"
OUTPUT="runs/checkpoints/wiki_level2_foundation_from_gold.pt"
MERGED="training_data/wiki_level_2_foundation_merged.md"
EPOCHS=3
LR="1e-5"
BATCH_SIZE=8
BLOCK_SIZE=256
SEED=1337
LOG_INTERVAL=10
DEVICE="cuda"
AMP_BF16=1
DRY_RUN=0

# Balanced default file set (foundational + deep-dive context)
FILES=(
  "training_data/wiki_level_2_v1_2.md"
  "training_data/wiki_level_3_dog_v1.md"
  "training_data/wiki_level_3_person_v1.md"
  "training_data/wiki_level_3_sun_moon_v1.md"
  "training_data/wiki_level_3_vehicle_v1.md"
  "training_data/wiki_level_3_world_map_v1.md"
  "training_data/wiki_level_3_weather_v1.md"
  "training_data/wiki_level_3_foundation_v1.md"
)

usage() {
  cat <<'USAGE'
Build merged Wiki foundation corpus and train BDH from a checkpoint.

Usage:
  ./run_wiki_level2_foundation.sh
  ./run_wiki_level2_foundation.sh --dry-run
  ./run_wiki_level2_foundation.sh --resume runs/checkpoints/my_base.pt --epochs 5 --lr 1e-5
  ./run_wiki_level2_foundation.sh --add-file training_data/my_extra_article.md

Options:
  --resume PATH         Base checkpoint (default: core/wiki_level1_from_phase1plus3_150m_e3.pt)
  --output PATH         Output checkpoint (default: runs/checkpoints/wiki_level2_foundation_from_gold.pt)
  --merged PATH         Merged corpus path (default: training_data/wiki_level_2_foundation_merged.md)
  --epochs N            Epochs (default: 3)
  --lr X                Learning rate (default: 1e-5)
  --batch-size N        Batch size (default: 8)
  --block-size N        Block size (default: 256)
  --seed N              Seed (default: 1337)
  --log-interval N      Log interval (default: 10)
  --device NAME         Device: cpu/cuda/mps (default: cuda)
  --no-amp-bf16         Disable bf16 autocast
  --add-file PATH       Append an extra source file to merge list (repeatable)
  --dry-run             Only build merged file; do not train
  --help                Show help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --resume) RESUME="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --merged) MERGED="$2"; shift 2 ;;
    --epochs) EPOCHS="$2"; shift 2 ;;
    --lr) LR="$2"; shift 2 ;;
    --batch-size) BATCH_SIZE="$2"; shift 2 ;;
    --block-size) BLOCK_SIZE="$2"; shift 2 ;;
    --seed) SEED="$2"; shift 2 ;;
    --log-interval) LOG_INTERVAL="$2"; shift 2 ;;
    --device) DEVICE="$2"; shift 2 ;;
    --no-amp-bf16) AMP_BF16=0; shift ;;
    --add-file) FILES+=("$2"); shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

[[ -x "$PYTHON" ]] || { echo "ERROR: Python runtime not executable: $PYTHON" >&2; exit 1; }
"$PYTHON" -c "import torch" >/dev/null 2>&1 || { echo "ERROR: torch not importable in $PYTHON" >&2; exit 1; }
[[ -f "$RESUME" ]] || { echo "ERROR: Resume checkpoint missing: $RESUME" >&2; exit 1; }

for f in "${FILES[@]}"; do
  [[ -f "$f" ]] || { echo "ERROR: Missing source file: $f" >&2; exit 1; }
done

mkdir -p "$(dirname "$MERGED")"

{
  echo "# Auto-merged Wiki Foundation Corpus"
  echo "# Generated by run_wiki_level2_foundation.sh"
  echo ""
  for f in "${FILES[@]}"; do
    echo "<!-- SOURCE: $f -->"
    cat "$f"
    echo ""
  done
} > "$MERGED"

BYTES=$(wc -c < "$MERGED" | tr -d ' ')
WORDS=$(wc -w < "$MERGED" | tr -d ' ')

echo "============================================================"
echo "  Wiki Level 2 Foundation Builder"
echo "============================================================"
echo "  Python: $PYTHON"
echo "  Resume: $RESUME"
echo "  Merged: $MERGED"
echo "  Size:   ${BYTES} bytes / ${WORDS} words"
echo "  Files:"
for f in "${FILES[@]}"; do
  echo "    - $f"
done

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo ""
  echo "Dry run complete. Training not started."
  exit 0
fi

mkdir -p "$(dirname "$OUTPUT")"

"$PYTHON" - <<PY
from pathlib import Path
import torch
import train

resume = Path(r"$RESUME")
output = Path(r"$OUTPUT")
merged = r"$MERGED"

device = torch.device(r"$DEVICE" if r"$DEVICE" else ("cuda" if torch.cuda.is_available() else "cpu"))
amp_bf16 = bool($AMP_BF16)
if amp_bf16 and device.type != "cuda":
    raise SystemExit("--no-amp-bf16 recommended when not on CUDA")

train.set_reproducibility(int($SEED))
train.PHASE_FILES[5] = [merged]

train.train(
    phase=5,
    resume=resume,
    output=output,
    epochs=int($EPOCHS),
    lr=float($LR),
    batch_size=int($BATCH_SIZE),
    block_size=int($BLOCK_SIZE),
    seed=int($SEED),
    log_interval=int($LOG_INTERVAL),
    grad_accum_steps=1,
    amp_bf16=amp_bf16,
    log_vram=(device.type == "cuda"),
    scale=False,
    scale_150m=True,
    device=device,
)
PY

echo ""
echo "Training complete."
echo "Checkpoint: $OUTPUT"
